### ISSUE TITLE
Using quality parameter gives "UnboundLocalError" message

### ISSUE THREAD

**Issue by jelabarre59** [wileyyugioh/kissanime_dl#18]
LinuxMint 18, kissanime-dl v1.9.1

Using parameter to select download quality gives "UnboundLocalError" message.

for command:
_kissanime-dl http://kissanime.to/Anime/Tetsujin-28-go-2004-Dub ~/Videos/Tetsujin28_2004dub --quality=360_
command throws error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init**.py", line 697, in getComplete
    dl_pkg = getSingle(dl_link, ses)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/**init**.py", line 681, in getSingle
    pure_link = getBlogspotUrls(link, ses, sleepy_time, quality_txt, verbose)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/vidextract.py", line 115, in getBlogspotUrls
    quality_txt + "\']/@value"
UnboundLocalError: local variable 'DOWNLOAD_URL_X_PATH' referenced before assignment

Running same command without "quality" switch works fine.

**Comment by wileyyugioh** [comment]
The bug was made when I started breaking down the spaghetti code that is the script. Should be fixed in https://github.com/wileyyugioh/kissanime_dl/commit/8bad9d39360a798dbd70106ba3257f745b2c2c41.
