### ISSUE TITLE
UnboundLocalError: 

### ISSUE THREAD

**Issue by ChiselTip** [wileyyugioh/kissanime_dl#19]
Seeing an error with version 1.9.1 when attempting to download from kissanime. This happens in both normal and --legacy mode. 

Platform: Linux
Python Version: 2
Program Version: 1.9.1
[.....]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init**.py", line 697, in getComplete
    dl_pkg = getSingle(dl_link, ses)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/**init**.py", line 681, in getSingle
    pure_link = getBlogspotUrls(link, ses, sleepy_time, quality_txt, verbose)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/vidextract.py", line 115, in getBlogspotUrls
    quality_txt + "\']/@value"
UnboundLocalError: local variable 'DOWNLOAD_URL_X_PATH' referenced before assignment

**Comment by wileyyugioh** [comment]
Can you try using the latest version on github? I believe a patch that hasn't been pushed live fixes this problem.

**Comment by wileyyugioh** [comment]
Should be fixed in version 1.9.2 which was pushed live.

**Comment by ChiselTip** [comment]
That seems to have taken care of it. 

Much appreciated!
