### ISSUE TITLE
Download failure trying to encode filename

### ISSUE THREAD

**Issue by ChiselTip** [wileyyugioh/kissanime_dl#21]
Example series here: /Anime/Blood 

The character it doesn't like is the '[ACUTE ACCENT](http://www.fileformat.info/info/unicode/char/b4/index.htm)'

[...]
Found file name: 
[(`w´)]_Blood+_-_01_[DVD_10bit][24124476]-r134.1

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl-1.9.2-py2.7.egg/kissanime_dl/__init**.py", line 702, in getComplete
    downloadFile(dl_pkg, dl_path, PATH_TO_HISTORY, url)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl-1.9.2-py2.7.egg/kissanime_dl/**init**.py", line 124, in downloadFile
    dl_name = cVunicode(url[NAME])
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl-1.9.2-py2.7.egg/kissanime_dl/**init**.py", line 120, in cVunicode
    return str(any)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 6: ordinal not in range(128)

[...]

Issue is in the [cVunicode function](https://github.com/wileyyugioh/kissanime_dl/blob/master/kissanime_dl/__init__.py#L117): 

I managed to work around it by replacing: 
    return unicode(any, utf8)
with 
    return any.encode('utf-8').strip()

Platform: Linux
Python Version: 2
Program Version: 1.9.2

**Comment by wileyyugioh** [comment]
Should be fixed in https://github.com/wileyyugioh/kissanime_dl/commit/eb4fb2c8b02425f105d52348d41f2ba067662d7f
