### ISSUE TITLE
Regex fails 

### ISSUE THREAD

**Issue by hex007** [wileyyugioh/kissanime_dl#4]
Regex fails for the following command. Request you to add debugging messages to regex on failure.
Example regex failure: 

```
Syntax/Pattern : '<div class='title'><a href="([^"]+)">([^<]+)<\a>'
Expected output : [1] : <HTTP URL> : "http://kissanime.to/Anime/Magi/my/url"
                  [2] : <TITLE>    : "Magi: The Labyrinth of Magic (Sub)"
Obtained Output : None
---------------------------------------------------------------------
AttributeError: 'NoneType' object has no attribute 'group'
```

```
,--(§åƙƐƫ)--(Running: 0)--(Fri Apr 01 06:38:37)--(【ツ】)---
`--(~$)--> kissanime-dl https://kissanime.to/Anime/Magi Videos/Magi
Checking for updates
Platform: Linux
Python Version: 2
Waiting for authentication...
Should take about 4 seconds
Success!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 729, in getDLUrls
    if(getOpenLoadUrls(queuee, ur, ses) == False):
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 650, in getOpenLoadUrls
    raw_data = re.search(r"""\$\('#divContentVideo'\)\.html\('<iframe sandbox="allow-forms allow-same-origin allow-scripts" style="width: 854px; height: 552px; border: 0px;" src="(.*?)\"""", html_str).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 729, in getDLUrls
    if(getOpenLoadUrls(queuee, ur, ses) == False):
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 650, in getOpenLoadUrls
    raw_data = re.search(r"""\$\('#divContentVideo'\)\.html\('<iframe sandbox="allow-forms allow-same-origin allow-scripts" style="width: 854px; height: 552px; border: 0px;" src="(.*?)\"""", html_str).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 729, in getDLUrls
    if(getOpenLoadUrls(queuee, ur, ses) == False):
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 650, in getOpenLoadUrls
    raw_data = re.search(r"""\$\('#divContentVideo'\)\.html\('<iframe sandbox="allow-forms allow-same-origin allow-scripts" style="width: 854px; height: 552px; border: 0px;" src="(.*?)\"""", html_str).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 729, in getDLUrls
    if(getOpenLoadUrls(queuee, ur, ses) == False):
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 650, in getOpenLoadUrls
    raw_data = re.search(r"""\$\('#divContentVideo'\)\.html\('<iframe sandbox="allow-forms allow-same-origin allow-scripts" style="width: 854px; height: 552px; border: 0px;" src="(.*?)\"""", html_str).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 729, in getDLUrls
    if(getOpenLoadUrls(queuee, ur, ses) == False):
  File "/usr/local/lib/python2.7/dist-packages/kissanime_dl/__init__.py", line 650, in getOpenLoadUrls
    raw_data = re.search(r"""\$\('#divContentVideo'\)\.html\('<iframe sandbox="allow-forms allow-same-origin allow-scripts" style="width: 854px; height: 552px; border: 0px;" src="(.*?)\"""", html_str).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-25[BD][720p][AAC]-r681
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-20[BD][720p][AAC]-r684
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-15[BD][720p][AAC]-r736
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-10[BD][720p][AAC]-r732
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-05[BD][720p][AAC]-r307
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-24[BD][720p][AAC]-r484
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-19[BD][720p][AAC]-r976
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-14[BD][720p][AAC]-r205
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-09[BD][720p][AAC]-r378
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-04[BD][720p][AAC]-r340
Beginning to download [DeadFish]Magi_TheLabyrinthofMagic-23[BD][720p][AAC]-r25
```

**Comment by wileyyugioh** [comment]
I plan to add this feature in the next update. The reason it is throwing errors now is because openload changed the javascript to find the url of the video, and I am currently looking into how the new system works.
